### ISSUE TITLE
Symmetric Dataset Annotation Guidelines

### ISSUE THREAD

**Issue by anam-zahid** [TalSchuster/FeverSymmetric#3]
Hi Tal,

I want to create symmetric datasets using the guidelines provided in the paper 'Towards debiasing fact verification models'. I want to ask if there are any other available annotator guidelines that we could follow for creating the symmetric datasets from various NLI corpora. 

Thanks

**Comment by TalSchuster** [comment]
Hi @anam-zahid ,

Thanks for reaching out. You might also want to look at [Get Your Vitamin C! Robust Fact Verification with Contrastive Evidence](https://arxiv.org/abs/2103.08541).
